project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "Advent_of_code"
  site-path: "/docs/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: YEARS/2022.qmd
        text: "2022"
      - href: YEARS/2023.qmd
        text: "2023"
      - href: https://github.com/jromanowska
        text: GitHub

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



