---
title: "Day 12"
author: "Julia Romanowska"
---

```{r setup, include = FALSE}
library(tidyverse)
library(here)
library(emoji)
```

## Data

Up, up, up, we are gonna climb!

The letters represent the levels, from `a` (lowest) to `z` (highest). We need
to get from `S` to `E` (which is on level `z`), but walking only one level up 
(or down) at a time.

```{r read_data}
levels_map <- map(
  readLines(
    here("DATA", "input_day_12.txt")
  ),
  function(line){
    str_split(line, pattern = "") %>% unlist()
  }
) %>% do.call(rbind, .)
dim(levels_map)
```

```{r plot}
levels_map %>%
  as_tibble(rownames = "row") %>%
  pivot_longer(cols = V1:V162, names_to = "col", values_to = "val") %>%
  mutate(
    col = as.numeric(str_sub(col, start = 2, end = -1)),
    row = as.numeric(row),
    val = factor(val, levels = c(letters, "E", "S"))
  ) %>%
  ggplot(aes(col, row)) +
  geom_tile(aes(fill = val)) +
  coord_fixed() +
  scale_fill_manual(
    values = c(grey((1:length(letters))/length(letters)), "#0000FF", "#FF0000"),
    name = ""
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal"
  )
```


